---
- name: build the code
  hosts: vagrant
  vars:
    mode: "{{ lookup('env','MODE') }}"
  environment:
    CYREST_SITE: "{{ lookup('env','CYREST_SITE') }}"
    CYREST_PROTO: "{{ lookup('env','CYREST_PROTO') }}"

  tasks:
    - name: clone the code
      git:
        repo: git@github.com:clickyab/clickyab-cyrest.git
        dest: "/home/cy/cyrest-{{ mode }}"
        force: yes

    - shell: git submodule update
      args:
        chdir: "/home/cy/cyrest-{{ mode }}"

    - shell: git checkout master && git pull
      args:
        chdir: "/home/cy/cyrest-{{ mode }}/front"

    - name: clean all data
      make:
        target: clean
        chdir: "/home/cy/cyrest-{{ mode }}"

    - name: get dependencies
      make:
        target: conditional-restore
        chdir: "/home/cy/cyrest-{{ mode }}"

    - name: generate codes
      make:
        target: codegen
        chdir: "/home/cy/cyrest-{{ mode }}"

    - name: generate codes
      make:
        target: codegen
        chdir: "/home/cy/cyrest-{{ mode }}"

    - name: create migration
      make:
        target: migration
        chdir: "/home/cy/cyrest-{{ mode }}"

    - name: build binaries
      make:
        target: all
        chdir: "/home/cy/cyrest-{{ mode }}"

    - name: make config file
      blockinfile:
        path: "/home/cy/cyrest-{{ mode }}/front/.env.js"
        block: |
          module.exports.webpack = {baseUrl: '{{ CYREST_PROTO }}://{{ CYREST_SITE }}'};

    - name: build front end
      make:
        target: build-js
        chdir: "/home/cy/cyrest-{{ mode }}"

# This is the staging build. it will build the app (using golang docker image) and run it with docker-compose
- name: staging build
  hosts: staging
  vars:
    mode: "{{ lookup('env','MODE') }}"

  environment:
    CYREST_DEVEL_MODE: "{{ lookup('env','CYREST_DEVEL_MODE') }}"
    MYSQL_USER: "{{ lookup('env','MYSQL_USER') }}"
    MYSQL_PASSWORD: "{{ lookup('env','MYSQL_PASSWORD') }}"
    MYSQL_DB: "{{ lookup('env','MYSQL_DB') }}"
    MYSQL_HOST: "{{ lookup('env','MYSQL_HOST') }}"
    MYSQL_PORT: "{{ lookup('env','MYSQL_PORT') }}"
    AMQP_USER: "{{ lookup('env','AMQP_USER') }}"
    AMQP_PASS: "{{ lookup('env','AMQP_PASS') }}"
    AMQP_HOST: "{{ lookup('env','AMQP_HOST') }}"
    AMQP_PORT: "{{ lookup('env','AMQP_PORT') }}"
    AMQP_VHOST: "{{ lookup('env','AMQP_VHOST') }}"
    REDIS_PASS: "{{ lookup('env','REDIS_PASS') }}"
    REDIS_PORT: "{{ lookup('env','REDIS_PORT') }}"
    REDIS_HOST: "{{ lookup('env','REDIS_HOST') }}"
    CYREST_SITE: "{{ lookup('env','CYREST_SITE') }}"
    CYREST_PROTO: "{{ lookup('env','CYREST_PROTO') }}"
    CYREST_TELEGRAM_API_KEY: "{{ lookup('env','CYREST_TELEGRAM_API_KEY') }}"
    CYREST_TELEGRAM_BOT_ID: "{{ lookup('env','CYREST_TELEGRAM_BOT_ID') }}"
    CYREST_TELEGRAM_BOT_NAME: "{{ lookup('env','CYREST_TELEGRAM_BOT_NAME') }}"
    VIRTUAL_HOST: "{{ lookup('env','CYREST_SITE') }}"

  tasks:
    - name: make sure docker compose installed and ready
      pip:
        name: docker-compose

    - name: Creates directory
      file:
        path: "/home/cy/cyrest"
        state: directory


    - name: copy go binary files to web servers
      synchronize:
        src: "/home/cy/cyrest-{{ mode }}/bin/"
        dest: "/home/cy/cyrest/bin/"
        delete: yes
        rsync_opts: "--exclude=.git --exclude=*.sh --exclude=gb* --exclude=go-bindata --exclude=fswatch --exclude=codegen"
        checksum: yes
        times: no
      delegate_to: 192.168.88.8

    - name: copy swagger files
      synchronize:
        src: "/home/cy/cyrest-{{ mode }}/3rd/swagger/"
        dest: "/home/cy/cyrest/swagger/"
        delete: yes
        checksum: yes
        times: no
      delegate_to: 192.168.88.8

    - name: copy frontend files
      synchronize:
        src: "/home/cy/cyrest-{{ mode }}/front/public/"
        dest: "/home/cy/cyrest/public/"
        delete: yes
        checksum: yes
        times: no
      delegate_to: 192.168.88.8

    - name: copy compose file to server
      synchronize:
        src: "{{ playbook_dir}}/"
        dest: "/home/cy/compose-{{ mode }}/"
        rsync_opts: "--exclude=.git --exclude=*.retry --exclude=staging*"
        delete: yes
        checksum: yes
        times: no
      delegate_to: 192.168.88.8

    - name: rename the correct compse
      command: mv "/home/cy/compose-{{ mode }}/docker-compose-{{ mode }}.yaml" "/home/cy/compose-{{ mode }}/docker-compose.yaml"

    - shell: docker-compose build
      args:
        chdir: "/home/cy/compose-{{ mode }}/"

    - shell: docker-compose up -d
      args:
        chdir: "/home/cy/compose-{{ mode }}/"

    - shell: docker-compose restart app cyborg got
      args:
        chdir: "/home/cy/compose-{{ mode }}/"
