#!/bin/bash

#set -eio pipefail

ansible-playbook release.yaml -i "${MODE}-hosts.ini" --extra-vars "CYREST_DEVEL_MODE=${CYREST_DEVEL_MODE} MYSQL_USER=${MYSQL_USER} MYSQL_PASSWORD=${MYSQL_PASSWORD} MYSQL_DB=${MYSQL_DB} MYSQL_HOST=${MYSQL_HOST} MYSQL_PORT=${MYSQL_PORT} AMQP_USER=${AMQP_USER} AMQP_PASS=${AMQP_PASS} AMQP_HOST=${AMQP_HOST} REDIS_PASS=${REDIS_PASS} REDIS_PORT=${REDIS_PORT} REDIS_HOST=${REDIS_HOST} CYREST_SITE=${CYREST_SITE} CYREST_PROTO=${CYREST_PROTO} CYREST_TELEGRAM_API_KEY=${CYREST_TELEGRAM_API_KEY} CYREST_TELEGRAM_BOT_ID=${CYREST_TELEGRAM_BOT_ID} CYREST_TELEGRAM_BOT_NAME=${CYREST_TELEGRAM_BOT_NAME} MODE=${MODE}"