swagger: "2.0"
info:
  version: 1.0.0
  title: The Cyrest API
  description: Auto genertaed Cyrest API
host: localhost
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /misc/version:
    get:
      description: getVersion get the version information
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/version_Version'
      tags:
      - misc
  /user:
    get:
      description: ""
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/user_listUserResponse'
        "401":
          description: you are not authorized
          schema:
            properties:
              error:
                type: string
            title: not_authorized
            type: object
        "403":
          description: forbidden, you have no access here
          schema:
            properties:
              error:
                type: string
            title: forbidden
            type: object
      parameters:
      - name: sort
        type: string
        description: ""
        in: query
        required: false
      - name: email
        type: 'string '
        description: ' search the email field'
        in: query
        required: false
      - name: status
        type: string
        description: ""
        in: query
        required: false
      - name: source
        type: string
        description: ""
        in: query
        required: false
      - name: token
        type: string
        description: the security token, get it from login route
        in: header
        required: true
      tags:
      - user
  /user/forgot/call:
    post:
      description: forgotPassword get email
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/base_NormalResponse'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
      parameters:
      - name: payload_data
        schema:
          $ref: '#/definitions/user_forgotPayload'
        description: ""
        in: body
        required: false
      tags:
      - user
  /user/forgot/callback/{code}:
    get:
      description: forgotGeneratePassword get email
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/base_NormalResponse'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
      parameters:
      - name: code
        type: string
        description: ""
        in: path
        required: true
      tags:
      - user
  /user/login:
    post:
      description: registerUser register user in system
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/user_responseLoginOK'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
      parameters:
      - name: payload_data
        schema:
          $ref: '#/definitions/user_loginPayload'
        description: ""
        in: body
        required: false
      tags:
      - user
  /user/logout:
    get:
      description: logout is for the logout from the system
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/base_NormalResponse'
        "401":
          description: you are not authorized
          schema:
            properties:
              error:
                type: string
            title: not_authorized
            type: object
        "403":
          description: forbidden, you have no access here
          schema:
            properties:
              error:
                type: string
            title: forbidden
            type: object
      parameters:
      - name: token
        type: string
        description: the security token, get it from login route
        in: header
        required: true
      tags:
      - user
  /user/register:
    post:
      description: registerUser register user in system
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/user_responseLoginOK'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
      parameters:
      - name: payload_data
        schema:
          $ref: '#/definitions/user_registrationPayload'
        description: ""
        in: body
        required: false
      tags:
      - user
  /user/session/terminate/{id}:
    get:
      description: ""
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/user_activeSessions'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
        "401":
          description: you are not authorized
          schema:
            properties:
              error:
                type: string
            title: not_authorized
            type: object
        "403":
          description: forbidden, you have no access here
          schema:
            properties:
              error:
                type: string
            title: forbidden
            type: object
      parameters:
      - name: id
        type: string
        description: ""
        in: path
        required: true
      - name: token
        type: string
        description: the security token, get it from login route
        in: header
        required: true
      tags:
      - user
  /user/sessions:
    get:
      description: ""
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/user_activeSessions'
        "401":
          description: you are not authorized
          schema:
            properties:
              error:
                type: string
            title: not_authorized
            type: object
        "403":
          description: forbidden, you have no access here
          schema:
            properties:
              error:
                type: string
            title: forbidden
            type: object
      parameters:
      - name: token
        type: string
        description: the security token, get it from login route
        in: header
        required: true
      tags:
      - user
  /user/sessions/terminate:
    get:
      description: ""
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/user_activeSessions'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
        "401":
          description: you are not authorized
          schema:
            properties:
              error:
                type: string
            title: not_authorized
            type: object
        "403":
          description: forbidden, you have no access here
          schema:
            properties:
              error:
                type: string
            title: forbidden
            type: object
      parameters:
      - name: token
        type: string
        description: the security token, get it from login route
        in: header
        required: true
      tags:
      - user
definitions:
  aaa_Session:
    properties:
      current:
        type: boolean
      expire_after:
        type: integer
      ip:
        type: string
      key:
        type: string
      user_agent:
        type: string
    type: object
  base_Column:
    properties:
      data:
        type: string
      filter:
        type: boolean
      filter_valid_map:
        additionalProperties:
          type:
            type: string
        type: object
      name:
        type: string
      searchable:
        type: boolean
      sortable:
        type: boolean
      title:
        type: string
      visible:
        type: boolean
    type: object
  base_ErrorResponseSimple:
    properties:
      error:
        type: string
    type: object
  base_NormalResponse:
    properties: {}
    type: object
  user_activeSessions:
    properties:
      more:
        type: boolean
      sessions:
        items:
          $ref: '#/definitions/aaa_Session'
        type: array
    type: object
  user_corporation:
    properties:
      company_name:
        type: string
      phone:
        type: string
    type: object
  user_forgotPayload:
    properties:
      email:
        type: string
    type: object
  user_listUserResponse:
    properties:
      data:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
      definition:
        items:
          $ref: '#/definitions/base_Column'
        type: array
      page:
        type: integer
      per_page:
        type: integer
      total:
        type: integer
    type: object
  user_loginPayload:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user_personal:
    properties:
      cellphone:
        type: string
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
    type: object
  user_registrationPayload:
    properties:
      corporation:
        $ref: '#/definitions/user_corporation'
      email:
        type: string
      password:
        type: string
      personal:
        $ref: '#/definitions/user_personal'
      source:
        type: string
    type: object
  user_responseLoginOK:
    properties:
      email:
        type: string
      token:
        type: string
      user_id:
        type: integer
    type: object
  version_Version:
    properties:
      build_date:
        format: dateTime
        type: string
      build_number:
        type: integer
      commit_date:
        format: dateTime
        type: string
      hash:
        type: string
      short_hash:
        type: string
    type: object
