swagger: "2.0"
info:
  version: 1.0.0
  title: The cyrest API
  description: Auto genertaed cyrest API
host: 127.0.0.1
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /misc/version:
    get:
      description: getVersion get the version information
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/version_Version'
      tags:
      - misc
  /user/forgot/call:
    post:
      description: forgotPassword get email
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/base_NormalResponse'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
      parameters:
      - name: payload_data
        schema:
          $ref: '#/definitions/user_forgotPayload'
        description: ""
        in: body
        required: false
      tags:
      - user
  /user/forgot/callback/{code}:
    get:
      description: forgotGeneratePassword get email
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/base_NormalResponse'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
      parameters:
      - name: code
        type: string
        description: ""
        in: path
        required: true
      tags:
      - user
  /user/register:
    post:
      description: registerUser register user in system
      responses:
        "200":
          description: ""
          produce: application/json
          schema:
            $ref: '#/definitions/user_responseLoginOK'
        "400":
          description: ""
          schema:
            $ref: '#/definitions/base_ErrorResponseSimple'
      parameters:
      - name: payload_data
        schema:
          $ref: '#/definitions/user_registrationPayload'
        description: ""
        in: body
        required: false
      tags:
      - user
definitions:
  base_ErrorResponseSimple:
    properties:
      error:
        type: string
    type: object
  base_NormalResponse:
    properties: {}
    type: object
  user_forgotPayload:
    properties:
      email:
        type: string
    type: object
  user_registrationPayload:
    properties:
      email:
        type: string
      password:
        type: string
      personal:
        type: boolean
    type: object
  user_responseLoginOK:
    properties:
      Accesstoken:
        type: string
      email:
        type: string
      user_id:
        type: integer
    type: object
  version_Version:
    properties:
      build_date:
        format: dateTime
        type: string
      build_number:
        type: integer
      commit_date:
        format: dateTime
        type: string
      hash:
        type: string
      short_hash:
        type: string
    type: object
