---
# This is the staging build. it will build the app (using golang docker image) and run it with docker-compose
- name: staging build
  hosts: staging

  tasks:
    - name: make sure docker.py is ready
      pip:
        name: docker-py

    - name: pull the changes
      git:
        repo: git@github.com:clickyab/clickyab-cyrest.git
        dest: /home/cy/cyrest
        accept_hostkey: True

#    - name: pull golang image
#      docker_image:
#        name: registry.clickyab.ae/clickyab/redis

    - name: pull mariadb image
      docker_image:
        name: registry.clickyab.ae/clickyab/mariadb

    - make:
        chdir: /home/cy/cyrest
        target: docker-build

    - name: run the mariadb server
      docker_container:
        name: golang-builder
        state: absent