---
# This is the staging build. it will build the app (using golang docker image) and run it with docker-compose
- name: staging build
  hosts: staging

  tasks:
    - name: make sure docker.py is ready
      pip:
        name: docker-py

    - name: pull the changes
      git:
        repo: git@github.com:clickyab/clickyab-cyrest.git
        dest: /home/cy/cyrest
        force: True
        accept_hostkey: True

    - name: pull redis image
      docker_image:
        name: registry.clickyab.ae/clickyab/redis

    - name: pull mariadb image
      docker_image:
        name: registry.clickyab.ae/clickyab/mariadb

    - name: build the code
      make:
        chdir: /home/cy/cyrest
        target: docker-build

    - name: run the mariadb server
      docker_container:
        name: mariadb-stash
        state: started
        image: registry.clickyab.ae/clickyab/mariadb
        recreate: False
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD=bita123

    - name: run the redis server
      docker_container:
        name: redis-stash
        state: started
        image: registry.clickyab.ae/clickyab/redis
        recreate: False
        ports:
          - "6379:6379"
    - name: wait for services to run
      pause:
        seconds: 20

    - name: create database
      make:
        chdir: /home/cy/cyrest
        target: mysql-createdb

    - name: do migrate
      make:
        chdir: /home/cy/cyrest
        target: migup

    - name: restart rubick ad
      shell: killall server