version: '2'
services:
  redis:
    image: "registry.clickyab.ae/clickyab/redis"
    ports:
      - "6379:6379"

  mysql:
    image: "registry.clickyab.ae/clickyab/mariadb"
    ports:
      - "3306:3306"
    volumes:
      - "/home/cy/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=bita123
      - MYSQL_DATABASE=cyrest

  rabbitmq:
    image: "registry.clickyab.ae/clicyab/rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=cyrest
      - RABBITMQ_DEFAULT_PASS=bita123

  tgcli:
    build: ./tgcli
    volumes:
      - "/home/cy/.telegram-cli:/root/.telegram-cli"
    command: tg

  app:
    build: ./image
    ports:
      - "80:80"
    volumes:
      - "/home/cy/cyrest:/app"
    command: /app/bin/server
    links:
      - mysql
      - redis
      - rabbitmq

  got:
    build: ./image
    volumes:
      - "/home/cy/cyrest:/app"
    command: /app/bin/got
    links:
      - mysql
      - redis
      - rabbitmq

  cyborg:
    build: ./image
    volumes:
      - "/home/cy/cyrest:/app"
    command: /app/bin/cyborg
    links:
      - mysql
      - redis
      - rabbitmq
      - tgcli